/**
 * 通道元数据 - 即时通讯应用
 * Channel metadata - Messaging apps
 * 
 * 包含: telegram, discord, slack, whatsapp, signal, line
 */
import type { ChannelMeta } from "../../../types/channel-config";
import {
  DM_POLICY_OPTIONS,
  GROUP_POLICY_OPTIONS,
  STREAM_MODE_OPTIONS,
  REACTION_LEVEL_OPTIONS,
  SELF_CHAT_MODE_OPTIONS,
  SLACK_MODE_OPTIONS,
} from "../../../types/channel-fields";

export const MESSAGING_APPS_CHANNELS: ChannelMeta[] = [
  {
    id: "telegram",
    label: "Telegram",
    icon: "telegram",
    description: "Telegram Bot 消息通道",
    docsUrl: "https://docs.molt.bot/channels/telegram",
    configFields: [
      { key: "enabled", label: "启用", type: "toggle", section: "basic" },
      { key: "botToken", label: "Bot Token", type: "password", placeholder: "123456:ABC-DEF...", required: true, section: "auth" },
      { key: "tokenFile", label: "Token 文件路径", type: "text", placeholder: "/path/to/token", section: "auth" },
      { key: "dmPolicy", label: "DM 策略", type: "select", options: DM_POLICY_OPTIONS, section: "access" },
      { key: "groupPolicy", label: "群组策略", type: "select", options: GROUP_POLICY_OPTIONS, section: "access" },
      { key: "streamMode", label: "流式模式", type: "select", options: [...STREAM_MODE_OPTIONS], section: "messaging" },
      { key: "textChunkLimit", label: "文本块限制", type: "number", placeholder: "4000", section: "messaging" },
      { key: "historyLimit", label: "群组历史记录限制", type: "number", placeholder: "50", section: "history" },
      { key: "dmHistoryLimit", label: "DM 历史记录限制", type: "number", placeholder: "50", section: "history" },
      { key: "linkPreview", label: "显示链接预览", type: "toggle", section: "messaging" },
      { key: "reactionLevel", label: "表情回应级别", type: "select", options: [...REACTION_LEVEL_OPTIONS], section: "messaging" },
    ],
  },
  {
    id: "discord",
    label: "Discord",
    icon: "discord",
    description: "Discord Bot 消息通道",
    docsUrl: "https://docs.molt.bot/channels/discord",
    configFields: [
      { key: "enabled", label: "启用", type: "toggle", section: "basic" },
      { key: "token", label: "Bot Token", type: "password", placeholder: "MTIzNDU2Nzg5...", required: true, section: "auth" },
      { key: "dmPolicy", label: "DM 策略", type: "select", options: DM_POLICY_OPTIONS, section: "access" },
      { key: "groupPolicy", label: "服务器策略", type: "select", options: GROUP_POLICY_OPTIONS, section: "access" },
      { key: "allowBots", label: "允许机器人消息", type: "toggle", section: "access" },
      { key: "textChunkLimit", label: "文本块限制", type: "number", placeholder: "2000", section: "messaging" },
      { key: "historyLimit", label: "历史记录限制", type: "number", placeholder: "50", section: "history" },
      { key: "dmHistoryLimit", label: "DM 历史记录限制", type: "number", placeholder: "50", section: "history" },
      { key: "maxLinesPerMessage", label: "每条消息最大行数", type: "number", placeholder: "17", section: "messaging" },
    ],
  },
  {
    id: "slack",
    label: "Slack",
    icon: "slack",
    description: "Slack App 消息通道",
    docsUrl: "https://docs.molt.bot/channels/slack",
    configFields: [
      { key: "enabled", label: "启用", type: "toggle", section: "basic" },
      { key: "mode", label: "连接模式", type: "select", options: [...SLACK_MODE_OPTIONS], section: "basic" },
      { key: "botToken", label: "Bot Token", type: "password", placeholder: "xoxb-...", required: true, section: "auth" },
      { key: "appToken", label: "App Token", type: "password", placeholder: "xapp-...", section: "auth" },
      { key: "userToken", label: "User Token", type: "password", placeholder: "xoxp-...", section: "auth" },
      { key: "dmPolicy", label: "DM 策略", type: "select", options: DM_POLICY_OPTIONS, section: "access" },
      { key: "groupPolicy", label: "频道策略", type: "select", options: GROUP_POLICY_OPTIONS, section: "access" },
      { key: "requireMention", label: "需要 @提及", type: "toggle", section: "access" },
      { key: "allowBots", label: "允许机器人消息", type: "toggle", section: "access" },
      { key: "textChunkLimit", label: "文本块限制", type: "number", placeholder: "4000", section: "messaging" },
      { key: "historyLimit", label: "历史记录限制", type: "number", placeholder: "50", section: "history" },
    ],
  },
  {
    id: "whatsapp",
    label: "WhatsApp",
    icon: "whatsapp",
    description: "WhatsApp Web 消息通道",
    docsUrl: "https://docs.molt.bot/channels/whatsapp",
    configFields: [
      { key: "enabled", label: "启用", type: "toggle", section: "basic" },
      { key: "authDir", label: "认证目录", type: "text", placeholder: "~/.clawdbot/whatsapp-auth", section: "auth" },
      { key: "dmPolicy", label: "DM 策略", type: "select", options: DM_POLICY_OPTIONS, section: "access" },
      { key: "groupPolicy", label: "群组策略", type: "select", options: GROUP_POLICY_OPTIONS, section: "access" },
      { key: "sendReadReceipts", label: "发送已读回执", type: "toggle", section: "messaging" },
      { key: "selfChatMode", label: "自聊模式", type: "select", options: [...SELF_CHAT_MODE_OPTIONS], section: "messaging" },
      { key: "textChunkLimit", label: "文本块限制", type: "number", placeholder: "4000", section: "messaging" },
      { key: "mediaMaxMb", label: "最大媒体大小 (MB)", type: "number", placeholder: "50", section: "messaging" },
      { key: "debounceMs", label: "防抖延迟 (ms)", type: "number", placeholder: "1000", section: "advanced" },
      { key: "historyLimit", label: "历史记录限制", type: "number", placeholder: "50", section: "history" },
    ],
  },
  {
    id: "signal",
    label: "Signal",
    icon: "signal",
    description: "Signal 消息通道",
    docsUrl: "https://docs.molt.bot/channels/signal",
    configFields: [
      { key: "enabled", label: "启用", type: "toggle", section: "basic" },
      { key: "account", label: "账号 (E.164)", type: "text", placeholder: "+1234567890", required: true, section: "auth" },
      { key: "httpUrl", label: "HTTP URL", type: "text", placeholder: "http://localhost:8080", section: "daemon" },
      { key: "httpHost", label: "HTTP Host", type: "text", placeholder: "127.0.0.1", section: "daemon" },
      { key: "httpPort", label: "HTTP Port", type: "number", placeholder: "8080", section: "daemon" },
      { key: "cliPath", label: "CLI 路径", type: "text", placeholder: "signal-cli", section: "daemon" },
      { key: "autoStart", label: "自动启动守护进程", type: "toggle", section: "daemon" },
      { key: "dmPolicy", label: "DM 策略", type: "select", options: DM_POLICY_OPTIONS, section: "access" },
      { key: "groupPolicy", label: "群组策略", type: "select", options: GROUP_POLICY_OPTIONS, section: "access" },
      { key: "sendReadReceipts", label: "发送已读回执", type: "toggle", section: "messaging" },
      { key: "textChunkLimit", label: "文本块限制", type: "number", placeholder: "4000", section: "messaging" },
      { key: "historyLimit", label: "历史记录限制", type: "number", placeholder: "50", section: "history" },
    ],
  },
  {
    id: "line",
    label: "LINE",
    icon: "line",
    description: "LINE Messaging API 通道",
    docsUrl: "https://docs.molt.bot/channels/line",
    configFields: [
      { key: "enabled", label: "启用", type: "toggle", section: "basic" },
      { key: "channelAccessToken", label: "Channel Access Token", type: "password", placeholder: "...", required: true, section: "auth" },
      { key: "channelSecret", label: "Channel Secret", type: "password", placeholder: "...", required: true, section: "auth" },
      { key: "webhookPath", label: "Webhook 路径", type: "text", placeholder: "/line", section: "webhook" },
      { key: "dmPolicy", label: "DM 策略", type: "select", options: DM_POLICY_OPTIONS, section: "access" },
      { key: "groupPolicy", label: "群组策略", type: "select", options: GROUP_POLICY_OPTIONS, section: "access" },
      { key: "textChunkLimit", label: "文本块限制", type: "number", placeholder: "5000", section: "messaging" },
      { key: "historyLimit", label: "历史记录限制", type: "number", placeholder: "50", section: "history" },
    ],
  },
];
